export const SET_SPINNER_FALSE = "SET_SPINNER_FALSE";
export const SET_SPINNER_TRUE = "SET_SPINNER_TRUE";
export const ADD_EVENT_VISIBLE = "ADD_EVENT_VISIBLE";
export const ADD_EVENT_HIDDEN = "ADD_EVENT_HIDDEN";
export const SET_EVENT_VALUE = "SET_EVENT_VALUE";
export const UNSET_EVENT_VALUE = "UNSET_EVENT_VALUE";
